### PR TITLE
Support Embark's URI imports

### PR DESCRIPTION
**Pull request by bakaoh**
Fix: #3

### CODE REVIEW

**Comment by andremedeiros** [comment]
Hey @bakaoh. Looks like you're going in the right direction! There's a couple of in-flight PRs that also support IPFS and swarm (embark-framework/embark#831, embark-framework/embark#847). Feel free to check those out for inspiration.

Keep up the good work.

**Comment by bakaoh** [comment]
thanks @jrainville , as you said, we can reuse what embark already done. Actually, this is just my quick implement to test the solution. 
Once this https://github.com/embark-framework/embark/pull/955 is merged, i will update the implement with minimum modification in this repo

**Comment by bakaoh** [comment]
@jrainville i updated the code

**Comment by jrainville** [comment]
It works well. Good job!

**Pull request merged**
